ain.ventures/ain.ventures/ui.ain.ventures/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Formatting;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using AIn.Ventures.Models;
using System.Diagnostics;

namespace AIn.Ventures.UI.Controllers
{
    public class ComponentController : Controller
    {
        Component RootComponent;

        private HttpClient CreateClient()
        {
            JWToken token = GetToken();

            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri("https://localhost:4243");

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token.AccessToken);

            return client;
        }

        private JWToken GetToken()
        {
            using (var client = new HttpClient())
            {
                var form = new Dictionary<string, string>
               {
                   {"grant_type", "password"},
                   {"username", "john.doe797@ain.ventures"},
                   {"password", "pwdPwd321!"},
               };
                var tokenResponse = client.PostAsync("https://localhost:4243/Token", new FormUrlEncodedContent(form)).Result;

                return tokenResponse.Content.ReadAsAsync<JWToken>(new[] { new JsonMediaTypeFormatter() }).Result;

            }

        }


        [HttpPost, Route("Module")]
        //[Authorize]
        public ActionResult CreateModule()
        {
            var cp = new Component();
            cp.ComponentType = "Module";
            cp.Name = Request["Name"];
            cp.Description = Request["Description"];
            cp.GUID = Guid.NewGuid();
            cp.ParentGUID = Guid.Parse(Request["ParentGUID"]);
            cp.AmountInParent = 1;
            cp.ProjectGUID = cp.ParentGUID;
            using (var client = CreateClient())
            {
                /*
                var ParGUID = new Guid("27acbb7c-075a-49bd-9b43-000eae3e6b6f");
                var newModule = new AIn.Ventures.Models.Component();
                newModule.ParentGUID = ParGUID;
                newModule.ProjectGUID = new Guid("820BF26F-4D0B-4630-9CC0-16205ED93759");
                newModule.GUID = Guid.NewGuid();
                newModule.Description = "Test description";
                newModule.Name = "Test name";
                newModule.Price = 0;
                newModule.SKU = "";
                newModule.Supplier = "";
                newModule.Manufacturer = "";
                */

                var result = client.PostAsJsonAsync<AIn.Ventures.Models.Component>("https://localhost:4243/Module", cp).Result;

                var r = result.Content.ReadAsStringAsync();

                return RedirectToAction(cp.ParentGUID.ToString(), "Module");
            }
        }
        [HttpPost, Route("Component/{ParentGUID}/{GUID}/{Amount}")]
        //[Authorize]
        public ActionResult CreateComponent(Guid ParentGUID,Guid GUID,int Amount)
        {
            var sparams = new AIn.Ventures.Models.QPoint();
            
            sparams.GUID = GUID;
            //sparams.Name = Name;

         //  sparams.AmountInParent = Amount;
            
            JsonResult res = new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
           
            using (var client = new HttpClient())
            {

               var response = client.PostAsync("https://localhost:4243/Component/"+ParentGUID.ToString()+"/"+GUID.ToString()+"/"+Amount.ToString(),new StringContent("")).Result;

             
                //res.Data = "Hello";
               //String r = response.Content.ReadAsAsync<string>(new[] { new JsonMediaTypeFormatter() }).Result;
                res.Data = response.StatusCode.ToString();

                return RedirectToAction(ParentGUID.ToString(), "Module");
            }
        }



        [HttpGet, Route("Module/{GUID}")]
        public ActionResult Index(Guid GUID)
        {



            //Guid RootGuid = new Guid("820bf26f-4d0b-4630-9cc0-16205ed93759");
            /*
            using (var client = new HttpClient())
            {
                var form = new Dictionary<string, string>
                {
                    {"grant_type", "password"},
                    {"username", "john5.doe@ain.ventures"},
                    {"password", "somePwd3456!"},
                };
                var tokenResponse = client.PostAsync("https://localhost:4243/Token", new FormUrlEncodedContent(form)).Result;

                token = tokenResponse.Content.ReadAsAsync<JWToken>(new[] { new JsonMediaTypeFormatter() }).Result;
            }
            */
            
            using (var client = AccountController.CreateClient())
            {
                var queryJson = client.GetStringAsync(String.Concat("https://localhost:4243/Module/", GUID)).Result;
                var Cmp = JsonConvert.DeserializeObject<Component>(queryJson);
                Cmp.GUID = GUID;
                RootComponent = Cmp;
            }
            /*
             * Debug return
             */
            //Component p = new Component
            //{
            //    GUID = Guid.NewGuid(),
            //    AmountInParent = 1,
            //    Children = new List<Component>
            //    {
            //        new Component
            //        {
            //            ComponentType = "Module",
            //            Description = "This goes in the other thing",
            //            Name = "spit",
            //            Manufacturer = "",
            //            MaxPrice = 100,
            //            MinPrice = 20,
            //            ParentGUID = Guid.NewGuid(),
            //            Price = 0,
            //            QPoints = new List<QPoint>(),
            //            SKU = "",
            //            SourceGUID = Guid.NewGuid(),
            //            Supplier = ""

            //        },
            //        new Component
            //        {
            //            ComponentType = "Module",
            //            Description = "This goes in the other thing",
            //            Name = "bubble gum",
            //            Manufacturer = "",
            //            MaxPrice = 100,
            //            MinPrice = 20,
            //            ParentGUID = Guid.NewGuid(),
            //            Price = 0,
            //            QPoints = new List<QPoint>(),
            //            SKU = "",
            //            SourceGUID = Guid.NewGuid(),
            //            Supplier = ""

            //        }


            //    },
            //    ComponentType = "Product",
            //    Description = "This thing rocks!",
            //    Name = "PU235 Immodium Space Modulator",
            //    Manufacturer = "",
            //    MaxPrice = 100,
            //    MinPrice = 20,
            //    ParentGUID = Guid.NewGuid(),
            //    Price = 0,
            //    QPoints = new List<QPoint>(),
            //    SKU = "",
            //    SourceGUID = Guid.NewGuid(),
            //    Supplier = ""
            //};
            //return View(p);

            return View("~/Views/Component/Index.cshtml", RootComponent);
        }

        //Get: Catalog
        [ChildActionOnly]
        [ActionName("_Category")]
        public ActionResult _Catalog()
        {
            var ctlg = new Catalog();
            List<Category> cats;
            JWToken token = new JWToken();
            // Don't need category because right now we just get the whole catalog
            // var CategoryName = Request["CategoryDropdown"];
            using (var client = new HttpClient())
            {
                var form = new Dictionary<string, string>
                {
                    {"grant_type", "password"},
                    {"username", "john5.doe@ain.ventures"},
                    {"password", "somePwd3456!"},
                };
                var tokenResponse = client.PostAsync("https://localhost:4243/Token", new FormUrlEncodedContent(form)).Result;

                token = tokenResponse.Content.ReadAsAsync<JWToken>(new[] { new JsonMediaTypeFormatter() }).Result;
            }

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:4243");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token.AccessToken);

                var queryJson = client.GetStringAsync("https://localhost:4243/Catalog/").Result;
                ctlg = JsonConvert.DeserializeObject<Catalog>(queryJson);
                cats = ctlg.Categories;

            }
            return PartialView(cats);

        }


        // Post: QPoint
        //[ChildActionOnly]
        [ActionName("_QPoint")]
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult _QPoint()
        {
            JWToken token = new JWToken();
            using (var client = new HttpClient())
            {
                var form = new Dictionary<string, string>
                {
                    {"grant_type", "password"},
                    {"username", "john5.doe@ain.ventures"},
                    {"password", "somePwd3456!"},
                };
                var tokenResponse = client.PostAsync("https://localhost:4243/Token", new FormUrlEncodedContent(form)).Result;

                token = tokenResponse.Content.ReadAsAsync<JWToken>(new[] { new JsonMediaTypeFormatter() }).Result;
                if (Request.Form.HasKeys())
                {

ain.ventures/ain.ventures/ui.ain.ventures/Controllers/QPointController.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web.Mvc;

namespace AIn.Ventures.UI.Controllers
{
    public class QPointController : Controller
    {
        [HttpPost, Route("QPoint")]
        //[Authorize]
        public ActionResult FindQPoints(List<string> Categories)
        {

            var sparams = new AIn.Ventures.Models.SearchParameters();
            sparams.Categories = Categories;
            JsonResult res = new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            /*Debug*/
            sparams.Categories = new List<string>();
            sparams.Categories.Add("Electronic Component.Integrated");
            /*Debug*/

            using (var client = new HttpClient())
            {
            
                /*
                List<string> cats = new List<string>();
                cats.Add("Electronic Component");
                cats.Add("Material.Element.Silicon");
                */

                var response = client.PostAsJsonAsync<AIn.Ventures.Models.SearchParameters>("https://localhost:4243/QPoint", sparams).Result;

                List<AIn.Ventures.Models.QPoint> r = response.Content.ReadAsAsync<List<AIn.Ventures.Models.QPoint>>(new[] { new JsonMediaTypeFormatter() }).Result;
                //string r = response.Content.ReadAsAsync<string>(new[] { new JsonMediaTypeFormatter() }).Result;

                res.Data = r;

                return res;
            }
        }
        }


    }

ain.ventures/ain.ventures/ui.ain.ventures/Views/Component/Index.cshtml
@using AIn.Ventures.Models
@model Component

@helper DrawComponent(Component mdl, int depth)
{
int padSize = 20;
string indent = String.Concat(depth * padSize, "px");
bool visible = depth == 0;
string display = visible ? "" : "display:none";
string id = "ListItem" + mdl.GUID;
if (mdl.ComponentType == "Module")
    {
        <div class='ModuleWrapper' id='@id' style='@display' data-visible='False'>
            <div class='ModuleHeader' >
                <div class="ModuleBullet" style='padding-left: @indent '>
                    <a data-action='toggleComponentDisplay' data-params='@id' class='HideArrow'>
                        <svg width='40' height='40'>
                            <polygon points='10,20 30,30 10,40' style='fill:white' />
                        </svg>
                    </a>
                </div>
                <div class='ModuleName'>
                    @mdl.Name
                </div>
                <div class='addIcon' id='@string.Concat("addIcon", mdl.GUID)' data-action='newComponentMenu' data-params='@mdl.GUID'>+</div>
                <div class='ModuleTransactionData'>
                    <!--white outline black border 1px and somehow get rid of border around textbox-->
                    <div class='ModuleAmountAndCost'>
                        <div class='AmountTextBoxWrapper'>
                            @Html.TextBox(String.Concat("Item", mdl.GUID, "Amount"), mdl.AmountInParent, new { @class = "AmountInput", id = @String.Concat("Item", mdl.GUID, "amountInputDiv") })
                            <div class='ScrubberUpArrow'>
                                <a class='ScrubberUpArrow'>
                                    &#9650;
                                </a>
                            </div>
                            <div class='ScrubberDownArrow'>
                                <a class='ScrubberDownArrow'>
                                    &#9660;
                                </a>
                            </div>
                        </div>
                        <div class='TimesSymbol'>
                            &times;
                        </div>
                        <div class='TotalModuleCost' id='@String.Concat("Item", mdl.GUID, "TotalCost")'>
                            $0.00
                        </div>
                    </div>
                </div>
                <div data-action='searchComponentMenu' id='@string.Concat("searchIcon", mdl.GUID)' >
                    <img  class='ModuleCommerceIcon' src='~/Images/commerce_icon.png' />
                </div>            
            </div>

            @{ 
                List<Component> Children = mdl.Children;
                foreach (var child in Children)
                {
                    @DrawComponent(child, depth + 1);
                }
            }
        </div>

    }
    else
    {
        var searchId = @String.Concat("SearchIcon", mdl.GUID);
        <div class='ModuleWrapper' style='@display' id='@id' data-visible='False'>
            <div class='ModuleHeader' id='@id'>
                <div id='ModulesTagDiv' style='padding-left: @indent'>
                    <img src='~/Images/rawcomponent_icon.png' class='RawComponentIcon' />
                </div>
                <div class='RawComponentDetails' id='@String.Concat(mdl.Name, "DetailsDiv")'>
                    <div class='ModuleComponentName'>
                        @mdl.Name
                    </div>
                    Manufacturer: @mdl.Manufacturer
                    SKU: @mdl.SKU
                </div>
                <div class='RawComponentEmptyEditCell'>
                    &nbsp;
                </div>
                <div class='ModuleTransactionData'>
                    <div class='ModuleAmountAndCost'>
                        <div class='AmountTextBoxWrapper'>
                            @Html.TextBox(@String.Concat(mdl.Name, "AmountInput"), @mdl.AmountInParent, new { @class = "AmountInput", id = @String.Concat(mdl.Name, "amountInputDiv") });
                            <div class='ScrubberUpArrow'>
                                <a class='ScrubberUpArrow'>
                                    &#9650;
                                </a>
                            </div>
                            <div class='ScrubberDownArrow'>
                                <a class='ScrubberDownArrow'>
                                    &#9660;
                                </a>
                            </div>
                        </div>

                    </div>
                    <div class='TimesSymbol'>
                        &times;
                    </div>
                    <div class='TotalModuleCost' id='@String.Concat(mdl.Name, "priceDiv")'>
                        @mdl.Price
                    </div>

                </div>
                <div class='CommerceElement'  id='@searchId'>
                    @if (mdl.SourceProduct == null)
                    {
                        <div data-action='showModal' data-params='{
                                                    "modalId":"SelectComponentModal", 
                                                    "triggerId":"@searchId", 
                                                    "leftOffset":-50,"topOffset":0, 
                                                    "callBack":"populateOrderList", 
                                                    "qPointGUID":"@mdl.GUID", 
                                                    "parentGUID": "@mdl.ParentGUID"
                             }'>
                            <img class='ComponentCommerceIcon' src='~/Images/search.svg'>
                        </div>
                    } else
                    {
                        @*<div>mdl.ParengGUID = @mdl.ParentGUID<br /> Model.GUID = @Model.GUID<br /> ObjectGUID = @mdl.GUID<br />Source = @mdl.SourceProduct.Source.Name<br />OrderID = @mdl.SourceProduct.ItemKey</div>*@

                    Html.RenderAction(String.Concat("_GetProduct"),
                                                new
                                                {
                                                    ParentGUID = mdl.ParentGUID,
                                                    ObjectGUID = mdl.GUID,
                                                });
                    }
                </div>
            </div>
            
        </div>
    }
}

    @{
        ViewBag.Title = String.Concat("Product: ", Model.Name, " - View");
    }

    <div id='modules'>
        <div id='ProductHeader' class='ProductHeader'>
            <div class='ProductBullet'>
                &gt;&gt;
            </div>
            <div class='ProductEmptyLeftCell'>
                &nbsp;&nbsp;&nbsp;&nbsp;
            </div>
            <div class='addIcon' id='@string.Concat("addIcon", Model.GUID)' data-action='newComponentMenu' data-params='@Model.GUID'>+</div>
            <div class='ProductCostAndIconsWrapper'>
                @Html.TextBox("ProductAmount", "1", new { @class = "AmountInput", id = @"ProductAmountInputDiv" })
                <div class='TimesSymbol'>
                    &times;
                </div>
                <div class='ScrubberArrows'>
                    <div class='ScrubberUpArrow'>
                        <a class='ScrubberUpArrow'>
                            &#9650;
                        </a>
                    </div>
                    <div class='ScrubberDownArrow'>
                        <a class='ScrubberDownArrow'>
                            &#9660;
                        </a>
                    </div>
                </div>
                <div class='TotalProjectCost' id="TotalProjectCost">
                    $0.00
                </div>
            </div>
            <div>
                <img class='ModuleCommerceIcon' src='~/Images/commerce_icon.png' />
            </div>
        </div>

        @{

            List<Component> Children = Model.Children;
            foreach (var child in Children)
            {
                @DrawComponent(child, 0);
            }
        }
    </div>

                        <div id='CreateComponentMenu' class='modal'>
                            <a id='NewModuleOption' data-showmodule='CreateModuleModal' data-moduleguid=''>
                                New Module
                            </a>
                            <a id='NewComponentOption' data-showmodule='AddComponentModal' data-moduleguid=''>
                                New Component
                            </a>
                            <div class='close-modal'>
                                x
                            </div>
                        </div>

                        <div id="CreateModuleModal" class='modal'>
                            @using (Html.BeginForm("", "Module", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-header"></div>
                                @*@Html.LabelFor(m=>m.Name)*@
                                <span>Name</span>
                                <div class="form-group">
                                    @Html.TextBox("Name", "", new { @class = "form-control" })
                                    @*@Html.ValidationMessageFor(m=>m.Name)*@
                                </div>
                                @*@Html.LabelFor(m=>m.Description)*@
                                <span>Description</span>
                                <div class="form-group">
                                    @Html.TextBox("Description", "", new { @class = "form-control" })
                                    @*@Html.ValidationMessageFor(m=>m.Description)*@
                                </div>
                                <div class="form-group">
                                    <div>
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>

                                @Html.Hidden("AmountInParent", 1)
                                @Html.Hidden("ParentGUID", Model.GUID, new { @class = "FormParentGUID" })

                            }
                            <div class="close-modal">
                                x
                            </div>
                        </div>

                        <div id="AddComponentModal" class='modal'>
                            <div id='QPointModalInput'>
                                <div>
                                    Catalog
                                </div>
                                <div id='CategoryList'>
                                    @Html.Action("_Category")
                                </div>
                            </div>
                            @{ var formName = "CategoryForm"; }
                            <div id='QPointModalOutput'>
                                <a data-action='clearQPointFilter'>Clear Filter</a>
                                @using (Ajax.BeginForm("_QPoint", "Component", new { }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "QPointList", InsertionMode = InsertionMode.Replace }, new { id = formName }))
        {
                                    <div id='CategoryList'>
                                        <textarea name='CategoryListTextArea' id='CategoryListTextArea'></textarea>
                                    </div>
                                    @Html.Hidden("ParentGUID", Model.GUID, new { @class = "FormParentGUID" })
                                }
                                <div id='QPointList'>
                                    @Html.Action("_QPoint", new List<QPoint>());
                                </div>

                            </div>
                            <div class='close-modal'>
                                x
                            </div>
                        </div>
                        <div id='SelectComponentModal' class='modal'>
                            <div id='ComponentList'>
                            </div>
                            <div class='close-modal'>
                                x
                            </div>
                        </div>

                        <script>
                            var updateForm = function () {
                                // Will be called on load and when the number of items
                                // in an order changes

                                // Go through each item in each raw component and
                                // multiply the cost times amount and add them up
                                // do the same for each submodule and so on
                            }
                        </script>

ain.ventures/ain.ventures/ui.ain.ventures/Views/Component/_AvailableProduct.cshtml
@model IEnumerable<AvailableProduct>
@{ 
    Layout = null;
}

@if(Model != null && Model.Count() > 0)
{
    foreach (var ap in Model){
        var url = string.Concat("_Commerce");
        <div id='@string.Concat("Product", ap.OrderID)' class='AvailableProduct'>
            @*call AssignToSource in Component Controller where itemKey = OrderID*@
            <a href='@ap.Url' target='_blank'>
                @ap.Name <br />
            </a>
            @*Sku: @ap.SKU <br />*@
            @ap.Manufacturer <br />
            $@ap.Price <br />
            <a  data-action='addProductToBasket' data-params='{
                                        "ParentGUID" :"@TempData["ParentGUID"]",
                                        "ObjectGUID" : "@TempData["ObjectGUID"]",
                                        "SourceName" : "@ap.Source.Name",
                                        "OrderID" : "@ap.OrderID"}'>
                Add To Basket
            </a>
            @*@using (Ajax.BeginForm(url,
                "Component",
                new { },
                new AjaxOptions { HttpMethod = "Post",
                    UpdateTargetId = string.Concat("SearchIcon", TempData["ObjectGUID"]),
                    InsertionMode = InsertionMode.Replace },
                new Dictionary<string, string> { { "id", string.Concat("OrderForm", ap.OrderID) }, { "data-action", "closeModals" } }))
            {
                <input type='submit' class='@string.Concat("OrderButton", ap.OrderID)' value='Add to Basket' />
                <input type='hidden' name='ParentGUID' value='@TempData["ParentGUID"]' />
                <input type='hidden' name='ObjectGUID' value='@TempData["ObjectGUID"]' />
                <input type='hidden' name='SourceName' value='@ap.Source.Name' />
                <input type='hidden' name='OrderID' value='@ap.OrderID' />
                //Html.Hidden("ParentGUID", TempData["ParentGUID"]);
                //Html.Hidden("ObjectGUID", TempData["ObjectGUID"]);
                //Html.Hidden("SourceName", ap.Source.Name);
                //Html.Hidden("OrderID", ap.OrderID);
            }*@
        </div>
        <hr />
    }
}
else
{
    <div>
        Sorry we can't find that product right now, but we'll look for it and get back to you!
    </div>
}

ain.ventures/ain.ventures/ui.ain.ventures/Views/Component/_Category.cshtml
@model List<Category>
@*@using AIn.Ventures.UI.App_Code*@
@helper MakeCategoryList(List<Category> cats, bool topLevel) {
    var listClass = "CategoryList";
    var ulDisplay = "none";
    var liDisplay = "block";

    if (topLevel)
    {
        listClass = "TopCategoryList";
        ulDisplay = "block";
        liDisplay = "none";
    }
    <ul class='@listClass' style='display:@ulDisplay'>
        @foreach (var c in cats)
        {
        var DivID = CategoryListMaker.sanitizeString(c.Name);
        <li class='CategoryListChildren' id='@DivID' style='display:@liDisplay'>
            <a data-action='revealChildren' data-params='@DivID'>
                +
            </a>
            <a data-action='addCategory' , data-params='@DivID'>
                @c.Name
            </a>
            @if (c.Categories.Count() > 0)
            {
                @MakeCategoryList(c.Categories, false);
            }
        </li>
        }
    </ul>

}
        <div>
            @using (Html.BeginForm())
            {
                <select data-change='revealTopLevelCategory' id='CategorySelect'>
                    <option value=''></option>
                    @foreach (var c in Model)
                    {
                        <option value='@CategoryListMaker.sanitizeString(c.Name)'>@c.Name</option>
                    }
                </select>
            }
        </div>
        @MakeCategoryList(Model, true)
        @*<ul id='TopCategoryList'>
            @foreach (Category c in Model)
            {
                var DivID = CategoryListMaker.sanitizeString(c.Name);
                <li class='CategoryListChildren' id='@DivID' style='display:none'>
                    <a data-action='revealChildren' data-params='@DivID'>
                        +
                    </a>
                    <a data-action='addCategory' , data-params='@DivID'>
                        @c.Name
                    </a>
                    @if (c.Categories.Count() > 0)
                    {

                        CategoryListMaker.MakeList(c.Categories);
                    }
                </li>
            }
        </ul>*@

ain.ventures/ain.ventures/ui.ain.ventures/Views/Component/_QPoint.cshtml
@model List<QPoint>

    @if (Model!=null && Model.Count() > 0)
    {
        <hr />

        int itemNum = 0;
        foreach (var item in Model)
        {
        <ul class='QPointListItem'>
            <li class='QPointListItemName'>
                @Html.DisplayFor(modelItem => item.Name)
            </li>
        </ul>

            itemNum++;
            String ParentGUID;
            if (TempData["ParentGUID"] != null) {
                ParentGUID = TempData["ParentGUID"].ToString();
            }
            else
            {
                ParentGUID = Guid.NewGuid().ToString();
            }
            int amountInParent = 1;
            using (Html.BeginForm(String.Concat( ParentGUID, "/", item.GUID, "/", amountInParent), "Component", FormMethod.Post, new { @class = "EnterQPointForm", id = "EnterQPointForm" }))
            {
                <input type = 'submit' value = 'Add to module' class='AddModuleButton' />
            }
        <hr />
        }
    }